dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage

script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test booth --keepdb
  - coverage xml
  - python-codacy-coverage -r coverage.xml

notifications:
  email:
    recipients:
      - josvilgar1@alum.us.es
    on_success: always
    on_failure: always
deploy:
  -provider: heroku
  app: decideapp
  strategy: git
  api_key: 86941d48-322b-4f80-a0d1-a38894a35f50
  on:
    branch: master

  -provider: heroku
  app: decideapp-2
  strategy: git
  api-key: 86941d48-322b-4f80-a0d1-a38894a35f50
  on:
    branch: travis